name: lightmeter
description: A new Flutter project.
publish_to: 'none'
version: 1.1.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sensors: ^2.0.0
  sensors_tizen:
    path: sensors
  wakelock: ^0.5.1
  wakelock_tizen: ^1.0.0
