name: lightmeter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sensors: ^0.4.2+6
  sensors_tizen:
    path: sensors

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
