name: lightmeter
description: A new Flutter project.
publish_to: "none"
version: 1.0.1

dependencies:
  flutter:
    sdk: flutter
  path_provider_tizen: ^2.0.0
  sensors: ^2.0.0
  sensors_tizen:
    path: sensors
  wakelock: ^0.5.1
  wakelock_tizen:
    path: ../plugins/packages/wakelock

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.9.0 <3.0.0'
  flutter: ">=2.0.0"
