name: lightmeter
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  path_provider_tizen: ^2.0.0
  sensors: ^2.0.0
  sensors_tizen:
    path: sensors

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/

environment:
  sdk: '>=2.9.0 <3.0.0'
  flutter: ">=2.0.0"
