name: lightmeter
description: A new Flutter project.
publish_to: 'none'
version: 1.1.1

dependencies:
  flutter:
    sdk: flutter
  sensors: ^2.0.0
  sensors_tizen:
    path: sensors
  wakelock: ^0.5.1
  wakelock_tizen:
    path: ../plugins/packages/wakelock

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'
